### ISSUE TITLE
Maquetar pantalla de información basica

### ISSUE THREAD

**Issue by Mengeroshi** [XpectreLabs/Cuidamed-Fronted#2]
- [x] Navbar Secundario

- [x] botones

- [x] inputs

- [x] selects

**Comment by Mengeroshi** [comment]
@LuisAlpachino  https://swiperjs.com/get-started/

**Comment by eduardojesus12** [comment]
Clasificación de campos.

Sexo: radiobutton
Fecha de nacimiento: date
Lugar de nacimiento: text
Pais de nacimiento: text
Altura: number
Peso: number
Tipo de sangre: select
Lugar de residencia: text
Pais de residencia: text
Grado maximo de estudios: select
Ocupacion: text
Religion: select
Estado civil: select
Donador de organos: select

**Comment by Mengeroshi** [comment]
- [x] Input text debe ser mas grande que el label  y de igual tamaño que el placeholder

- [x] Todos  los input text deben estar alineados a la izquieda y ala  misma que el label

- [x] el label cuando se posisiona en la parte superior debe ir un poco mas ala izquierda

- [x] Espaciado entre el label y input

- [x] input date D-MM-YYYY

- [x] Todos los inputs deben tener label

@LuisAlpachino @eduardojesus12

**Comment by Mengeroshi** [comment]
- [x] Corregir el calendario

- [x] centrar los input type number y hacer las flechas mas grandes y que esten por deafault, no solo al momento del hover

- [x] Corregir el bug de ubicacion

- [x] el orden del grado de estudios es de mayor a menor

@SergioSosaGonzalez @LuisAlpachino  @eduardojesus12
